In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('emails.csv')

In [6]:
df.head()

   Unnamed: 0                                               Body  Label
0           0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1           1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2           2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3           3  ##############################################...      1
4           4  I thought you might like these:\n1) Slim Down ...      1

In [7]:
df.shape

(6046, 3)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6046 entries, 0 to 6045
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6046 non-null   int64
 1   Body        6045 non-null   object
 2   Label       6046 non-null   int64
dtypes: int64(2), object(1)
memory usage: 141.8+ KB

In [9]:
df.isnull().sum()

Unnamed: 0    0
Body          1
Label         0
dtype: int64

In [10]:
df.drop_duplicates(inplace=True)
df['Label'] = df['Label'].astype(str)
df.drop(columns="Unnamed: 0", inplace=True)

In [11]:
df.head()

                                                Body Label
0  \nSave up to 70% on Life Insurance.\nWhy Spend...     1
1  1) Fight The Risk of Cancer!\nhttp://www.adcli...     1
2  1) Fight The Risk of Cancer!\nhttp://www.adcli...     1
3  ##############################################...     1
4  I thought you might like these:\n1) Slim Down ...     1

In [12]:
df.sample(10)

                                                   Body Label
5938  -----BEGIN PGP SIGNED MESSAGE-----CERT Advisor...     0
656   \nÂ Â \nDear \n                        Homeown...     1
2796  When a settler goes postal and kills some Pale...     0
196   THE ULTIMATE WAY TO WORK FROM HOME \nTHE BEST ...     1
5743  Hi Thor,[Still trying to catch my breath] :-)I...     0
2382  unwritten rule.  8-)gg-----Original Message---...     0
3631  \nBecause I get mail through several different...     0
1957                                              empty     0
4374  \nI don't know how one can expect better and m...     0
4811  Partitioning is an ambiguous term\nbut I think...     0

In [13]:
df['Body'] = df['Body'].astype(str).str.lower()

In [14]:
df.head()

                                                Body Label
0  \nsave up to 70% on life insurance.\nwhy spend...     1
1  1) fight the risk of cancer!\nhttp://www.adcli...     1
2  1) fight the risk of cancer!\nhttp://www.adcli...     1
3  ##############################################...     1
4  i thought you might like these:\n1) slim down ...     1

In [15]:
pip install nltk

Requirement already satisfied: nltk in c:\users\adity\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\adity\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\adity\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\adity\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\adity\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\adity\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\adity\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\adity\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\adity\anaconda3\Lib\site-packages)

In [16]:
import nltk

nltk.download("punkt")
nltk.download("stopwords")
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\adity\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\adity\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\adity\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [17]:
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps = PorterStemmer()

def transform_text(text):

    # lowercase
    text = text.lower()

    # tokenize
    words = word_tokenize(text)

    # keep only letters and numbers
    words = [word for word in words if word.isalnum()]

    # remove stopwords
    words = [word for word in words if word not in stopwords.words('english')]

    # stemming
    words = [ps.stem(word) for word in words]

    return " ".join(words)

In [18]:
pip install tqdm

Requirement already satisfied: tqdm in c:\users\adity\anaconda3\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in c:\users\adity\anaconda3\lib\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\adity\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\adity\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\adity\anaconda3\Lib\site-packages)

In [19]:
from tqdm import tqdm
tqdm.pandas()
df['Body'] = df['Body'].progress_apply(transform_text)

100%|██████████████████████████████████████████████████████████████████████████████| 6046/6046 [05:36<00:00, 17.95it/s]

In [20]:
df.head()

                                                Body Label
0  save 70 life insur spend life quot save ensur ...     1
1  1 fight risk cancer http slim guarante lose lb...     1
2  1 fight risk cancer http slim guarante lose lb...     1
3  adult club offer free membership instant acces...     1
4  thought might like 1 slim guarante lose lb 30 ...     1

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
tfidf = TfidfVectorizer(
    max_features=5000
)

In [24]:
X = tfidf.fit_transform(df['Body'])

In [25]:
y = df['Label']

In [26]:
print(X.shape)

(6046, 5000)

In [27]:
print(y.shape)

(6046,)

In [28]:
print(tfidf.get_feature_names_out()[:20])

['00' '000000' '0033ff' '01' '02' '02131' '03' '04' '05' '06' '07' '08'
 '08039' '09' '10' '100' '1000' '101' '1024' '105th']

In [30]:
X_df = pd.DataFrame(
    X.toarray(),
    columns = tfidf.get_feature_names_out()
)

In [31]:
df.head()

                                                Body Label
0  save 70 life insur spend life quot save ensur ...     1
1  1 fight risk cancer http slim guarante lose lb...     1
2  1 fight risk cancer http slim guarante lose lb...     1
3  adult club offer free membership instant acces...     1
4  thought might like 1 slim guarante lose lb 30 ...     1

In [32]:
df.sample()

                                                   Body Label
1169  blast bed blast bed guarante final safe natur ...     1

In [33]:
X_df.head()

,00,000000,0033ff,01,02,02131,03,04,05,06,...,zero,ziggi,zimbabw,zip,zone,zoom,zoomâ,zope,zowi,zzzz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.236605
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.059897
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,model.predict(X_test))

0.9495867768595041